### ISSUE TITLE
Severity syslog-а не отображается правильно на значения уровней логгирования

### ISSUE THREAD

**Issue by pasviridov** [yandex-cloud/fluent-bit-plugin-yandex#14]
Если мы забираем сообщения из syslog-а и задаем уровень логгирования как ```level_key PRIORITY``` (для Ubuntu 22.04), то в значении level приходят [числа "0" ... "7"](https://docs.delphix.com/docs53/system-administration/system-monitoring/setting-syslog-preferences/severity-levels-for-syslog-messages). Плагин ожидает вместо этих значений строковые представления уровней логгирования Yandex Cloud Logging. В итоге любой severity отображается на ```logging.LogLevel_LEVEL_UNSPECIFIED``` - сообщения в группу пишутся просто без уровня. Возможно, проблему можно как-то решить парсерами, но мне пока не понятно как.

Для себя я исправил проблему, пропатчив файл ```yclient\util.go```, но выглядит не очень правильно, хоть и работает:

```go
var (
    // https://docs.delphix.com/docs53/system-administration/system-monitoring/setting-syslog-preferences/severity-levels-for-syslog-messages
    syslog_severity_LogLevel_Level = map[string]logging.LogLevel_Level{
        "0": logging.LogLevel_FATAL,
        "1": logging.LogLevel_ERROR,
        "2": logging.LogLevel_ERROR,
        "3": logging.LogLevel_ERROR,
        "4": logging.LogLevel_WARN,
        "5": logging.LogLevel_WARN,
        "6": logging.LogLevel_INFO,
        "7": logging.LogLevel_DEBUG,
    }
)

func levelFromString(level string) (logging.LogLevel_Level, error) {
    if v, ok := logging.LogLevel_Level_value[strings.ToUpper(level)]; ok {
        return logging.LogLevel_Level(v), nil
    }
    if v, ok := syslog_severity_LogLevel_Level[level]; ok {
        return v, nil
    }
    return logging.LogLevel_LEVEL_UNSPECIFIED, fmt.Errorf("bad level: %q", level)
}
```

**Comment by nikolaymatrosov** [comment]
Этому не место в Output плагине. Почему? Потому что другому пользователю нужен будет другой маппинг. Он может кодировать дебаг логи минимальным значением `0`, а чем выше приоритет тем большее значение передавать. Или в другой системе может другое распределение уровней и с 1 по 5 — это все WARN. Или уровни логирования могут быть закодированы лишь одной первой буквой: `D`, `I`, `W`, `E` и `F`.

Все варианты предусмотреть нельзя, да и как видно выше некоторые из них будут конфликтовать по логике маппинга.

Если вы хотите добавить маппинг каких либо параметров записи лога, это стоит делать в фильтрах. Например [так](https://nikolaymatrosov.medium.com/wasm-фильтры-в-fluentbit-f444769aac27).

**Comment by pasviridov** [comment]
Я не претендовал на правильность решения. Было очевидно, что так, как я написал, делать неправильно. Я лишь обратил внимание на проблему: в ваших руководствах (в т.ч. [в доках по Yandex.Cloud](https://cloud.yandex.ru/docs/logging/tutorials/vm-fluent-bit-logging) ) по подключению этой службы ни про какие маппинги ничего не сказано. И если все сделать так, как в них написано, то запись логов в облако работает некорректно. Думаю стоит, как минимум, добавить последний абзац вашего комментария (вместе со ссылкой) в руководство из документации.
