### ISSUE TITLE
обновите плагин под новую версию

### ISSUE THREAD

**Issue by fzk273** [yandex-cloud/fluent-bit-plugin-yandex#19]
здравствуйте!
шёл по инструкции из документации: https://cloud.yandex.ru/docs/logging/tutorials/vm-fluent-bit-logging
столкнулся с рядом проблем при установке на ubuntu jammy невозможно установить версию td-agent из документации.
так же при установке и настройке последней версии и доступных версий из репозитория при запуске сталкиваюсь с такой ошибкой:
[error] [config] section 'yc-logging' tried to instance a plugin name that don't exists
пожалуйста обновите версию плагина или документацию для возможности успешной настройке на сервере

**Comment by nikolaymatrosov** [comment]
Поддержка Jammy появилась в версии [1.9.6](https://github.com/fluent/fluent-bit/issues/5374).
Вы можете использовать ту же самую инструкцию, просто поменяв версии компилятора Go и FluentBit на [соответствующие](https://github.com/yandex-cloud/fluent-bit-plugin-yandex/blob/main/Dockerfile#L2-L3).

**Comment by nikolaymatrosov** [comment]
Я прошел инструкцию с изменениями, которые я указал выше: версия Go и версия FluentBit. Все работает.

**Comment by fzk273** [comment]
добрый день. прошу прощения у меня была ошибка в конфиге. закрывайте issue
