### ISSUE TITLE
Adopt plugin code to changes of Message format in v2.1

### ISSUE THREAD

**Issue by wizard1024** [yandex-cloud/fluent-bit-plugin-yandex#21]
Docker image: cr.yandex/yc/fluent-bit-plugin-yandex:v2.1.0-fluent-bit-2.1.7@sha256:86245f83db6a194c0bcec608521c97915cd88483440e65ef159100200f5a4d84

I saw a lot of error messages:
time provided invalid, defaulting to now.

How to reproduce:
fluent-bit.conf:
```
[INPUT]
    Name  tail
    Path  /opt/test.log

[Output]
    Name yc-logging
    Match *
    resource_type test
    resource_id   nginx
    stream_name  stdout
    message_key log
    default_level INFO
    authorization instance-service-account
```

Possible cause:
Event format
The Fluent Bit wire protocol represents an Event as a 2-element array with a nested array as the first element:
[[TIMESTAMP, METADATA], MESSAGE]
where
TIMESTAMP is a timestamp in seconds as an integer or floating point value (not a string);
METADATA is a possibly-empty object containing event metadata; and
MESSAGE is an object containing the event body.
Fluent Bit versions prior to v2.1.0 instead used:
[TIMESTAMP, MESSAGE]
to represent events. This format is still supported for reading input event streams.

[https://docs.fluentbit.io/manual/concepts/key-concepts#event-format](https://docs.fluentbit.io/manual/concepts/key-concepts#event-format)

But i see:
plugin/plugin.go
```
func (p *Plugin) Transform(provider nextRecordProvider, tag string) map[model.Resource][]*model.Entry {
        resourceToEntries := make(map[model.Resource][]*model.Entry)

        for {
                ret, ts, record := provider()
                if ret != 0 {
                        break
                }

                entry, res, err := p.entry(toTime(ts), record, tag)
...
```

**Comment by kruftik** [comment]
I believe it is already supported by #20, I am still waiting for a new build is released

**Comment by wizard1024** [comment]
After updating to latest docker image, error messages disappeared.
