### ISSUE TITLE
Обновление до актуального FluentBit

### ISSUE THREAD

**Issue by AnvilFox1965** [yandex-cloud/fluent-bit-plugin-yandex#4]
Добрый день!

Обновите по возможности, пожалуйста. Там по multiline-парсеру работы проведены были, очень хочется разобраться и потестировать.

Спасибо!

**Comment by candiduslynx** [comment]
спасибо, сделаем

**Comment by candiduslynx** [comment]
https://github.com/yandex-cloud/fluent-bit-plugin-yandex/releases/tag/v1.2.0
