### ISSUE TITLE
No binaries?

### ISSUE THREAD

**Issue by FractalizeR** [yandex-cloud/fluent-bit-plugin-yandex#7]
Hello, guys.

Documentation neither in README here nor [in the Cloud](https://cloud.yandex.ru/docs/logging/tutorials/vm-fluent-bit-logging) says where to get binaries. I'm controlling my infra with Terraform / Ansible and this isn't very convenient for me to compile pluign on each host.

Release notes say something about images. Which images are those? I don't use docker BTW.

**Comment by candiduslynx** [comment]
Images can be found in the [releases](https://github.com/yandex-cloud/fluent-bit-plugin-yandex/releases)
As for the binaries, we don't provide them now.
